#!/bin/bash


initToolchainConfiguration()
{
    FM_CONFIG_ARCHITECTURE="${FM_GLOBAL_ARCHITECTURE}"
    FM_CONFIG_ADDRESS_MODEL="${FM_GLOBAL_ADDRESS_MODEL}"
    FM_CONFIG_CROSS_COMPILER_HOST="${FM_GLOBAL_CROSS_COMPILER_HOST}"
    FM_CONFIG_BUILD_VARIANT=""

    FM_CONFIG_COMMON_CFLAGS=""
    FM_CONFIG_COMMON_CXXFLAGS=""
    FM_CONFIG_COMMON_LDFLAGS=""
    FM_CONFIG_ARCHITECTURE_CFLAGS="${FM_GLOBAL_CFLAGS}"
    FM_CONFIG_ARCHITECTURE_CXXFLAGS="${FM_GLOBAL_CXXFLAGS}"
    FM_CONFIG_ARCHITECTURE_LDFLAGS="${FM_GLOBAL_LDFLAGS}"
    FM_CONFIG_BUILD_VARIANT_CFLAGS=""
    FM_CONFIG_BUILD_VARIANT_CXXFLAGS=""
    FM_CONFIG_BUILD_VARIANT_LDFLAGS=""

    case ${FM_ARG_BUILD_VARIANT} in
        debug)
            FM_CONFIG_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            FM_CONFIG_BUILD_VARIANT_CFLAGS="-g"
        ;;
        release)
            FM_CONFIG_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            FM_CONFIG_BUILD_VARIANT_CFLAGS="-O2"
        ;;
        profile)
            FM_CONFIG_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            FM_CONFIG_BUILD_VARIANT_CFLAGS="-O2 -g"
        ;;
        *)
            error "Invalid variant ${FM_ARG_BUILD_VARIANT}. Valid values are (debug, release, profile)"
    esac

    FM_TARGET_HAS_DLLS="false"
    FM_TARGET_ARCHITECTURE="${FM_CONFIG_ARCHITECTURE}"
    FM_TARGET_ADDRESS_MODEL="${FM_CONFIG_ADDRESS_MODEL}"
    FM_TARGET_CROSS_COMPILER_HOST="${FM_CONFIG_CROSS_COMPILER_HOST}"
    FM_TARGET_BUILD_VARIANT="${FM_CONFIG_BUILD_VARIANT}"
}

initToolchainTools()
{
    FM_CONFIG_COMMON_CFLAGS="-I${FM_LIBS_INSTALL_INCLUDES} -fPIC -Wextra -Wall -W --sysroot=${FM_GLOBAL_SYSROOT}"
    FM_CONFIG_COMMON_CXXFLAGS="-std=gnu++1y"
    FM_CONFIG_COMMON_LDFLAGS="-L${FM_LIBS_INSTALL_LIBS}"
    
    FM_TARGET_TOOLCHAIN_CFLAGS="${FM_CONFIG_COMMON_CFLAGS} ${FM_CONFIG_ARCHITECTURE_CFLAGS} ${FM_CONFIG_BUILD_VARIANT_CFLAGS}"
    FM_TARGET_TOOLCHAIN_CXXFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS} ${FM_CONFIG_COMMON_CXXFLAGS} ${FM_CONFIG_ARCHITECTURE_CXXFLAGS} ${FM_CONFIG_BUILD_VARIANT_CXXFLAGS}"
    FM_TARGET_TOOLCHAIN_LDFLAGS="${FM_CONFIG_COMMON_LDFLAGS} ${FM_CONFIG_ARCHITECTURE_LDFLAGS} ${FM_CONFIG_BUILD_VARIANT_LDFLAGS}"

    FM_TARGET_TOOLCHAIN_AR="${FM_CONFIG_CROSS_COMPILER_HOST}-ar"
    FM_TARGET_TOOLCHAIN_CC="${FM_CONFIG_CROSS_COMPILER_HOST}-gcc"
    FM_TARGET_TOOLCHAIN_CXX="${FM_CONFIG_CROSS_COMPILER_HOST}-g++"
    FM_TARGET_TOOLCHAIN_NM="${FM_CONFIG_CROSS_COMPILER_HOST}-nm"
    FM_TARGET_TOOLCHAIN_RANLIB="${FM_CONFIG_CROSS_COMPILER_HOST}-ranlib"

    export AR="${FM_TARGET_TOOLCHAIN_AR}"
    export CC="${FM_TARGET_TOOLCHAIN_CC}"
    export CXX="${FM_TARGET_TOOLCHAIN_CXX}"
    export NM="${FM_TARGET_TOOLCHAIN_NM}"
    export RANLIB="${FM_TARGET_TOOLCHAIN_RANLIB}"

    export CFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS}"
    export CXXFLAGS="${FM_TARGET_TOOLCHAIN_CXXFLAGS}"
    export LDFLAGS="${FM_TARGET_TOOLCHAIN_LDFLAGS}"
}


FM_TARGET_PLATFORM="${FM_GLOBAL_TARGET}_gcc"
FM_TARGET_TOOLCHAIN="linux_gcc"
FM_TARGET_TOOLCHAIN_HOST_OS="linux"
FM_TARGET_TOOLCHAIN_VERSION="$(${FM_GLOBAL_CROSS_COMPILER_HOST}-gcc -dumpversion)"
if [ ${#FM_TARGET_TOOLCHAIN_VERSION} -le 2 ]; then
    FM_TARGET_TOOLCHAIN_VERSION="$(${FM_GLOBAL_CROSS_COMPILER_HOST}-gcc -dumpfullversion)"
fi
