#!/bin/bash
#-----------------------------------------------------------------------------------------------------------------------
# Copyright (C) 2021 Fabrizio Maj
#
# This file is part of the cpp_libs_build_scripts project, which is distributed under the MIT license.
# Refer to the licenses of the managed libraries for conditions on their use and distribution.
# For details, see https://github.com/fabriz/cpp_libs_build_scripts
#-----------------------------------------------------------------------------------------------------------------------

initToolchain()
{
    local LOCAL_ARCHITECTURE_SUFFIX="$(echo ${FM_ARG_ARCHITECTURE} | tr '[:lower:]' '[:upper:]')"
    local LOCAL_BUILD_VARIANT_SUFFIX="$(echo ${FM_ARG_BUILD_VARIANT} | tr '[:lower:]' '[:upper:]')"

    local LOCAL_VAR_NAME_ARCHITECTURE_CFLAGS="FM_TARGET_TOOLCHAIN_ARCHITECTURE_CFLAGS_${LOCAL_ARCHITECTURE_SUFFIX}"
    local LOCAL_VAR_NAME_ARCHITECTURE_CXXFLAGS="FM_TARGET_TOOLCHAIN_ARCHITECTURE_CXXFLAGS_${LOCAL_ARCHITECTURE_SUFFIX}"
    local LOCAL_VAR_NAME_ARCHITECTURE_LDFLAGS="FM_TARGET_TOOLCHAIN_ARCHITECTURE_LDFLAGS_${LOCAL_ARCHITECTURE_SUFFIX}"

    local LOCAL_VAR_NAME_BUILD_VARIANT_CFLAGS="FM_TARGET_TOOLCHAIN_BUILD_VARIANT_CFLAGS_${LOCAL_BUILD_VARIANT_SUFFIX}"
    local LOCAL_VAR_NAME_BUILD_VARIANT_CXXFLAGS="FM_TARGET_TOOLCHAIN_BUILD_VARIANT_CXXFLAGS_${LOCAL_BUILD_VARIANT_SUFFIX}"
    local LOCAL_VAR_NAME_BUILD_VARIANT_LDFLAGS="FM_TARGET_TOOLCHAIN_BUILD_VARIANT_LDFLAGS_${LOCAL_BUILD_VARIANT_SUFFIX}"

    FM_TARGET_ARCHITECTURE="${FM_ARG_ARCHITECTURE}"
    FM_TARGET_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"

    case ${FM_ARG_ARCHITECTURE} in
        armv7|x86)
            FM_TARGET_ADDRESS_MODEL="32"
        ;;
        armv8|x86_64)
            FM_TARGET_ADDRESS_MODEL="64"
        ;;
        *)
            error "Invalid architecture '${FM_ARG_ARCHITECTURE}'."
        ;;
    esac
    
    FM_TARGET_TOOLCHAIN_CPPFLAGS="-I${FM_LIBS_INSTALL_INCLUDES} ${FM_TARGET_TOOLCHAIN_COMMON_CPPFLAGS-}"
    FM_TARGET_TOOLCHAIN_CFLAGS="${FM_TARGET_TOOLCHAIN_COMMON_CFLAGS-} ${!LOCAL_VAR_NAME_ARCHITECTURE_CFLAGS-} ${!LOCAL_VAR_NAME_BUILD_VARIANT_CFLAGS-}"
    FM_TARGET_TOOLCHAIN_CXXFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS} ${FM_TARGET_TOOLCHAIN_COMMON_CXXFLAGS-} ${!LOCAL_VAR_NAME_ARCHITECTURE_CXXFLAGS-} ${!LOCAL_VAR_NAME_BUILD_VARIANT_CXXFLAGS-}"
    FM_TARGET_TOOLCHAIN_LDFLAGS="-L${FM_LIBS_INSTALL_LIBS} ${FM_TARGET_TOOLCHAIN_COMMON_LDFLAGS-} ${!LOCAL_VAR_NAME_ARCHITECTURE_LDFLAGS-} ${!LOCAL_VAR_NAME_BUILD_VARIANT_LDFLAGS-}"

    export AR="${FM_TARGET_TOOLCHAIN_AR}"
    export CC="${FM_TARGET_TOOLCHAIN_CC}"
    export CXX="${FM_TARGET_TOOLCHAIN_CXX}"
    export NM="${FM_TARGET_TOOLCHAIN_NM}"
    export RANLIB="${FM_TARGET_TOOLCHAIN_RANLIB}"

    export CPPFLAGS="${FM_TARGET_TOOLCHAIN_CPPFLAGS}"
    export CFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS}"
    export CXXFLAGS="${FM_TARGET_TOOLCHAIN_CXXFLAGS}"
    export LDFLAGS="${FM_TARGET_TOOLCHAIN_LDFLAGS}"

    export FM_LIBS_INSTALL_PREFIX
    export CMAKE_GENERATOR="${FM_TARGET_CMAKE_GENERATOR}"
    export PKG_CONFIG_PATH=${FM_LIBS_INSTALL_PKGCONFIG}:${PKG_CONFIG_PATH-}
}
