#!/bin/bash


initToolchain()
{
    local LOCAL_ARCHITECTURE=""
    local LOCAL_ADDRESS_MODEL=""
    local LOCAL_BUILD_VARIANT=""

    local LOCAL_COMMON_CPPFLAGS=""
    local LOCAL_COMMON_CFLAGS=""
    local LOCAL_COMMON_CXXFLAGS=""
    local LOCAL_COMMON_LDFLAGS=""
    local LOCAL_ARCHITECTURE_CFLAGS=""
    local LOCAL_ARCHITECTURE_CXXFLAGS=""
    local LOCAL_ARCHITECTURE_LDFLAGS=""
    local LOCAL_BUILD_VARIANT_CFLAGS=""
    local LOCAL_BUILD_VARIANT_CXXFLAGS=""
    local LOCAL_BUILD_VARIANT_LDFLAGS=""

    case ${FM_ARG_ARCHITECTURE} in
        x86)
            LOCAL_ARCHITECTURE="x86"
            LOCAL_ARCHITECTURE_CFLAGS=""
            LOCAL_ADDRESS_MODEL="32"
        ;;
        x86_64)
            LOCAL_ARCHITECTURE="x86_64"
            LOCAL_ARCHITECTURE_CFLAGS="-arch x86_64"
            LOCAL_ADDRESS_MODEL="64"
        ;;
        *)
            error "Invalid architecture '${FM_ARG_ARCHITECTURE}'."
        ;;
    esac

    case ${FM_ARG_BUILD_VARIANT} in
        debug)
            LOCAL_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            LOCAL_BUILD_VARIANT_CFLAGS="-g"
        ;;
        release)
            LOCAL_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            LOCAL_BUILD_VARIANT_CFLAGS="-O2"
        ;;
        profile)
            LOCAL_BUILD_VARIANT="${FM_ARG_BUILD_VARIANT}"
            LOCAL_BUILD_VARIANT_CFLAGS="-O2 -g"
        ;;
        *)
            error "Invalid build variant '${FM_ARG_BUILD_VARIANT}'."
        ;;
    esac

    FM_TARGET_ARCHITECTURE="${LOCAL_ARCHITECTURE}"
    FM_TARGET_ADDRESS_MODEL="${LOCAL_ADDRESS_MODEL}"
    FM_TARGET_BUILD_VARIANT="${LOCAL_BUILD_VARIANT}"

    LOCAL_COMMON_CPPFLAGS="-I${FM_LIBS_INSTALL_INCLUDES}"
    LOCAL_COMMON_CFLAGS="-fPIC -Wextra -Wall -W -mmacosx-version-min=10.10"
    LOCAL_COMMON_CXXFLAGS="-stdlib=libc++ -std=c++14"
    LOCAL_COMMON_LDFLAGS="-L${FM_LIBS_INSTALL_LIBS}"
    
    FM_TARGET_TOOLCHAIN_CPPFLAGS="${LOCAL_COMMON_CPPFLAGS} ${FM_TARGET_TOOLCHAIN_COMMON_CPPFLAGS-}"
    FM_TARGET_TOOLCHAIN_CFLAGS="${LOCAL_COMMON_CFLAGS} ${LOCAL_ARCHITECTURE_CFLAGS} ${LOCAL_BUILD_VARIANT_CFLAGS}"
    FM_TARGET_TOOLCHAIN_CXXFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS} ${LOCAL_COMMON_CXXFLAGS} ${LOCAL_ARCHITECTURE_CXXFLAGS} ${LOCAL_BUILD_VARIANT_CXXFLAGS}"
    FM_TARGET_TOOLCHAIN_LDFLAGS="${LOCAL_COMMON_LDFLAGS} ${LOCAL_ARCHITECTURE_LDFLAGS} ${LOCAL_BUILD_VARIANT_LDFLAGS}"

    FM_TARGET_TOOLCHAIN_AR="ar"
    FM_TARGET_TOOLCHAIN_CC="clang"
    FM_TARGET_TOOLCHAIN_CXX="clang++"
    FM_TARGET_TOOLCHAIN_NM="nm"
    FM_TARGET_TOOLCHAIN_RANLIB="ranlib"

    export AR="${FM_TARGET_TOOLCHAIN_AR}"
    export CC="${FM_TARGET_TOOLCHAIN_CC}"
    export CXX="${FM_TARGET_TOOLCHAIN_CXX}"
    export NM="${FM_TARGET_TOOLCHAIN_NM}"
    export RANLIB="${FM_TARGET_TOOLCHAIN_RANLIB}"

    export CPPFLAGS="${FM_TARGET_TOOLCHAIN_CPPFLAGS}"
    export CFLAGS="${FM_TARGET_TOOLCHAIN_CFLAGS}"
    export CXXFLAGS="${FM_TARGET_TOOLCHAIN_CXXFLAGS}"
    export LDFLAGS="${FM_TARGET_TOOLCHAIN_LDFLAGS}"
}
