#!/bin/bash

export FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY}/vars.sh"

export FM_TARGET_OS_TYPE=linux
export FM_TARGET_COMPILER=gcc
export FM_TARGET_TOOLCHAIN=linux_gcc
export FM_TARGET_PLATFORM=linux_gcc
export FM_TARGET_HAS_PKGCONFIG=true
export FM_TARGET_ALL_ARCHITECTURES=x86_64
export FM_TARGET_ALL_BUILD_VARIANTS=debug,release,profile

export FM_TARGET_TOOLCHAIN_AR=ar
export FM_TARGET_TOOLCHAIN_CC=gcc
export FM_TARGET_TOOLCHAIN_CXX=g++
export FM_TARGET_TOOLCHAIN_NM=nm
export FM_TARGET_TOOLCHAIN_RANLIB=ranlib

export FM_TARGET_TOOLCHAIN_COMMON_CFLAGS="-fPIC -Wextra -Wall -W"
export FM_TARGET_TOOLCHAIN_COMMON_CXXFLAGS="-std=gnu++1y"
export FM_TARGET_TOOLCHAIN_COMMON_LDFLAGS=""

export FM_TARGET_TOOLCHAIN_BUILD_VARIANT_CFLAGS_DEBUG="-g"
export FM_TARGET_TOOLCHAIN_BUILD_VARIANT_CFLAGS_RELEASE="-O2"
export FM_TARGET_TOOLCHAIN_BUILD_VARIANT_CFLAGS_PROFILE="-O2 -g"

export FM_TARGET_COMPILER_VERSION="$(${FM_TARGET_TOOLCHAIN_CC} -dumpversion)"
if [ ${#FM_TARGET_COMPILER_VERSION} -le 2 ]; then
    export FM_TARGET_COMPILER_VERSION="$(${FM_TARGET_TOOLCHAIN_CC} -dumpfullversion)"
fi

source "${FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY}/start_bash.sh"
