@echo off

set FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY=%~dp0
call "%FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY%\vars.bat"

set PATH=%FM_CONFIG_MINGW_64_INSTALL_PATH%\bin;^
%FM_CONFIG_MSYS64_INSTALL_PATH%\usr\local\bin;^
%FM_CONFIG_MSYS64_INSTALL_PATH%\usr\bin;^
%FM_CONFIG_MSYS64_INSTALL_PATH%\bin;^
%FM_CONFIG_MSYS64_INSTALL_PATH%\opt\bin;^
%PATH%

set FM_TARGET_OS_TYPE=windows
set FM_TARGET_COMPILER=gcc
set FM_TARGET_TOOLCHAIN=windows_mingw
set FM_TARGET_PLATFORM=windows_mingw
set FM_TARGET_HAS_PKGCONFIG=true
set FM_TARGET_ALL_ARCHITECTURES=x86_64
set FM_TARGET_ALL_BUILD_VARIANTS=debug,release,profile

for /F "delims=" %%i in ('gcc -dumpversion') do set FM_TARGET_COMPILER_VERSION=%%i

set FM_TARGET_BUILD_FLAGS_FOR_BOOST=--without-python

call "%FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY%\start_bash.bat"
