@echo off

cd /D %FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY%\..\..

%FM_CONFIG_MSYS64_INSTALL_PATH%\usr\bin\bash.exe --rcfile "%FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY%\start_bash.sh" -i

cd /D %FM_PATH_ENVIRONMENT_INIT_SCRIPT_DIRECTORY%
